# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
